server:
  port: 8095

spring:
  data:
    mongodb:
      uri: mongodb+srv://root:welcome1@mongo-starter.dg69c.mongodb.net/BOOKSTORE?retryWrites=true&w=majority
  #      uri: mongodb://root:welcome1@127.0.0.1:27017/BOOKSTORE?authSource=admin
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 9508faaec7c87635f03e
            clientSecret: ebaa0cf40f246bef88d181e6145bba0e5515402c

springdoc:
  swagger-ui:
    oauth:
      clientId: 9508faaec7c87635f03e
      clientSecret: ebaa0cf40f246bef88d181e6145bba0e5515402c
    oauth2-redirect-url: http://localhost:8095/webjars/swagger-ui/oauth2-redirect.html
    csrf:
      enabled: true
  oAuthFlow:
    authorizationUrl: https://github.com/login/oauth/authorize
    tokenUrl: http://localhost:8095/login/oauth2/code/github
